 <h1 align=center><font size = 5> Repaso de Python</font></h1>
 
 *Josh Wills define un Data Scientist como un programador que sabe más de estadística que cualquier programador y como un estadistico que sabe más de programación que cualquier estadistico*
 
 **Este pensamiento nos lleva a que la comprensión del lenguaje de programacion de Pytjon de forma correcta es fundamental para el desarrollo de un Data Scientist.**

<img src="https://www.cedesistemas.edu.co/sitio/wp-content/themes/andreco/images/logo.png" width=400, align = "right">

* **CEDESISTEMAS**
* **DIPLOMADO BIG DATA -ANALITICA DE DATOS**



**Facilitador Academico :**
**Oscar Andres Gaspar Alvarez**

**Medellin - Mayo del 2020**


<a id="ref7"></a>

## Tabla de contenido

* <p><a href="#ref1"> 1) Librerias para ML </a></p>
* <p><a href="#ref2"> 2) Funciones </a></p>
* <p><a href="#ref3"> 3) Estructura de Datos</a></p>
* <p><a href="#ref4"> 4) Importacion de Archivos</a></p>



<a id="ref1"></a>
## Librerias para ML

<p><a href="#ref7"><font color = red size = 3> Inicio</font> </a></p>


* **Numpy** :NumPy es una biblioteca de Python muy popular para el procesamiento de matrices y matrices multidimensionales de gran tamaño
* **Scipy** : SciPy es una biblioteca muy popular entre los entusiastas del aprendizaje automático, ya que contiene diferentes módulos para optimización, álgebra lineal, integración y estadísticas.
* **Scikit-learn** : Skikit-learn es una de las bibliotecas ML más populares para algoritmos ML clásicos. Está construido sobre dos bibliotecas básicas de Python, a saber, NumPy y SciPy. Scikit-learn admite la mayoría de los algoritmos de aprendizaje supervisados ​​y no supervisados.
* **Theano** Todos sabemos que Machine Learning es básicamente matemática y estadística. Theano es una popular biblioteca de Python que se utiliza para definir, evaluar y optimizar expresiones matemáticas que involucran matrices multidimensionales de manera eficiente. Se logra optimizando la utilización de la CPU y la GPU. Se usa ampliamente para pruebas unitarias y autoverificaciones para detectar y diagnosticar diferentes tipos de errores.
* **TensorFlow** : TensorFlow es una biblioteca de código abierto muy popular para el cómputo numérico de alto rendimiento desarrollado por el equipo de Google Brain en Google. Como su nombre lo indica, Tensorflow es un marco que implica definir y ejecutar cálculos que involucran tensores. Puede entrenar y ejecutar redes neuronales profundas que pueden usarse para desarrollar varias aplicaciones de IA
* **Keras** : Keras es una biblioteca de Machine Learning muy popular para Python. Es una API de redes neuronales de alto nivel capaz de ejecutarse sobre TensorFlow, CNTK o Theano. Se puede ejecutar sin problemas tanto en la CPU como en la GPU. Keras hace que sea realmente para principiantes de ML construir y diseñar una red neuronal.
* **PyTorch** : PyTorch es una biblioteca de aprendizaje automático de código abierto popular para Python basada en Torch, que es una biblioteca de aprendizaje automático de código abierto que se implementa en C con un contenedor en Lua. Tiene una amplia selección de herramientas y bibliotecas que admite la visión por computadora, el procesamiento del lenguaje natural (PNL) y muchos más programas de ML. Permite a los desarrolladores realizar cálculos en tensores con aceleración de GPU y también ayuda a crear gráficos computacionales.
* **Pandas** : Pandas es una biblioteca de Python popular para el análisis de datos. No está directamente relacionado con el aprendizaje automático. Como sabemos, el conjunto de datos debe estar preparado antes del entrenamiento. 
* **Matplotlib** : Matpoltlib es una biblioteca Python muy popular para la visualización de datos. Al igual que Pandas, no está directamente relacionado con el aprendizaje automático. Es particularmente útil cuando un programador quiere visualizar los patrones en los datos

<a id="ref2"></a>
## **Funciones**

<p><a href="#ref7"><font color = red size = 3> Inicio</font> </a></p>


In [1]:
import numpy as np
import pandas as pd

### Creación de funciones

In [2]:
def Suma_dos_Numeros(x, y):
    return x + y

Suma_dos_Numeros(1, 2)

3

**Tomar un tercer parámetro opcional. El uso printpermite la impresión de múltiples expresiones dentro de una sola celda.**

In [3]:
def Suma_dos_Numeros(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(Suma_dos_Numeros(1, 2)) ## tomo dos parametros
print(Suma_dos_Numeros(1, 2, 3)) ### Tomo tres Parametros

3
6


**Asignar Una función a una  variable A**

In [4]:
def Suma_dos_Numeros(x,y):
    return x+y

a = Suma_dos_Numeros
a(1,2)

3

<a id="ref3"></a>
## **Estructura de Datos**

<p><a href="#ref7"><font color = red size = 3> Inicio</font> </a></p>



**Conocer Tipo de datos**

In [5]:
nombre = "Jaime"
type(nombre)

str

In [6]:
Numero=235
type(Numero)

int

In [7]:
Decimal =2.5
type(Decimal)

float

In [8]:
type(Suma_dos_Numeros)

function

**Listas**

Una lista es una estructura de datos y un tipo de dato en python con características especiales. Lo especial de las listas en Python es que nos permiten almacenar cualquier tipo de valor como enteros, cadenas y hasta otras funciones; por ejemplo:

In [9]:
lista = [1, 2.5, 'DevCode', [5,6] ,4]

**Acceder a una lista**

In [10]:
lista[0] ## Empieza en cero

1

In [11]:
lista[1]

2.5

In [12]:
lista[-1] ## conocer el ultimo dato

4

**Agregar Nuevos Datos a la Lista**

In [13]:
lista.append(10) 
lista.append([2,5]) 
lista

[1, 2.5, 'DevCode', [5, 6], 4, 10, [2, 5]]

**Extend también nos permite agregar elementos dentro de una lista, pero a diferencia de append al momento de agregar una lista, cada elemento de esta lista se agrega como un elemento más dentro de la otra lista.**

In [14]:
lista.extend([2,5])
lista

[1, 2.5, 'DevCode', [5, 6], 4, 10, [2, 5], 2, 5]

**Tuplas**

En Python, una tupla es un conjunto ordenado e inmutable de elementos del mismo o diferente tipo.

Las tuplas se representan escribiendo los elementos entre paréntesis y separados por comas.

In [15]:
x = (1, 'a', 2, 'b')
type(x) ## las Tuplas no se pueden Cambiar el contenido

tuple

**Diccionarios**

Un Diccionario es una estructura de datos y un tipo de dato en Python con características especiales que nos permite almacenar cualquier tipo de valor como enteros, cadenas, listas e incluso otras funciones. Estos diccionarios nos permiten además identificar cada elemento por una clave (Key).

Para definir un diccionario, se encierra el listado de valores entre llaves. Las parejas de clave y valor se separan con comas, y la clave y el valor se separan con dos puntos.

In [16]:
diccionario = {'nombre' : 'Carlos', 'edad' : 22, 'cursos': ['Python','Django','JavaScript'] }
print(diccionario)


{'nombre': 'Carlos', 'edad': 22, 'cursos': ['Python', 'Django', 'JavaScript']}


Podemos acceder al elemento de un Diccionario mediante la clave de este elemento, como veremos a continuación:

In [17]:
print (diccionario['nombre'] )#Carlos
print(diccionario['edad']) #22
print (diccionario['cursos']) #['Python','Django','JavaScript']

Carlos
22
['Python', 'Django', 'JavaScript']


## Fechas y Horas

In [18]:
import datetime as dt
import time as tm

**Time devuelve el tiempo actual en segundos desde la época. (1 de enero de 1970)**

In [19]:
tm.time()

1588806867.774379

**Convertir lo anterior en Fecha y Hora**

In [20]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 5, 6, 18, 14, 27, 786347)

**Atributos**

In [21]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2020, 5, 6, 18, 14, 27)

**Hora Local**

In [22]:
today = dt.date.today()
today 

datetime.date(2020, 5, 6)

## Operaciones con Numericas con Numpy 

In [23]:
import numpy as np

**Creando Arrays**

**Desde una lista  a un arreglo**

In [24]:
mylist = [1, 2, 3] ## 
x = np.array(mylist)
x

array([1, 2, 3])

**Directemente**

In [25]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

**Multidimensional**

In [26]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

**Conocer la Dimension**

In [27]:
m.shape

(2, 3)

**Iterando sobre Arreglos**

In [28]:
test = np.random.randint(0, 10, (4,3)) ## Matriz 4 por 3
test

array([[6, 9, 1],
       [4, 5, 5],
       [8, 7, 9],
       [3, 1, 4]])

**Iterando Por Filas**

In [29]:
for row in test:
    print(row)

[6 9 1]
[4 5 5]
[8 7 9]
[3 1 4]


**Iterar por Indice**

In [30]:
for i in range(len(test)):
    print(test[i])

[6 9 1]
[4 5 5]
[8 7 9]
[3 1 4]


**Iterando por Fila e Indice**

In [31]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [6 9 1]
row 1 is [4 5 5]
row 2 is [8 7 9]
row 3 is [3 1 4]


**SERIES**

In [32]:
import pandas as pd
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype=None,
    name=None,
    copy=False,
    fastpath=False,
)
Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, *, **) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series.

    .. versionchanged:: 0.23.0
       If data is a dict, argument order is maintained for Python 3.6
       and later.

index : array-like or Index (1d)
    Values must 

In [33]:
Variables = ['Nombre', 'Direccion', 'Cargo']
pd.Series(Variables)

0       Nombre
1    Direccion
2        Cargo
dtype: object

In [34]:
Numeros = [1, 2, 3]
pd.Series(Numeros )

0    1
1    2
2    3
dtype: int64

In [35]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
## Convertimos diccionario en una Serie
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [36]:
s.iloc[3] ## Acceder

'South Korea'

In [37]:
s.loc['Golf']

'Scotland'

In [38]:
s[3]

'South Korea'

In [39]:
s['Golf']

'Scotland'

In [40]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)

In [41]:
s.iloc[0]

'Bhutan'

In [42]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

**Crear con mas variables**

In [43]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [44]:
all_countries 

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
Cricket        Australia
Cricket         Barbados
Cricket         Pakistan
Cricket          England
dtype: object

In [45]:
original_sports

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [46]:
cricket_loving_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [47]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

## DataFrame

In [48]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

**Consultando**

In [49]:
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                      5
Name: Store 2, dtype: object

**Tipo**

In [50]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [51]:
df.loc['Store 1']

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [52]:
df.loc['Store 1', 'Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

**Trasponer**

In [53]:
df.T

Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5          5

In [54]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2       5
Name: Cost, dtype: object

In [55]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [56]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [57]:
df.loc[:,['Name', 'Cost']]

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

**Borrar**

In [58]:
df.drop('Store 1')

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [59]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

**CREAR COPIA**

In [60]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [61]:
copy_df.drop?

Signature:
copy_df.drop(
    labels=None,
    axis=0,
    index=None,
    columns=None,
    level=None,
    inplace=False,
    errors='raise',
)
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by specifying directly index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level.

Parameters
----------
labels : single label or list-like
    Index or column labels to drop.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or list-like
    Alternative to specifying axis (``labels, axis=0``
    is equivalent to ``index=labels``).

    .. versionadded:: 0.21.0
columns : single label or list-like
    Alternative to specifying axis (``labels, axis=1``
    is equivalent to ``columns=labels``).

    .. versionadded:: 0.21.0
level : int or level name, op

**BORRAR VARIABLE**

In [62]:
del copy_df['Name']
copy_df

Item Purchased  Cost
Store 2      Bird Seed   5.0

**Crear Variable**

In [63]:
df['Location'] = None
df

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  22.5     None
Store 1  Kevyn   Kitty Litter   2.5     None
Store 2  Vinod      Bird Seed   5.0     None

**Indexación y carga de Dataframes**

In [64]:
costs = df['Cost']
costs

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [65]:
costs+=2 # Sumando Variable
costs

Store 1    24.5
Store 1     4.5
Store 2     7.0
Name: Cost, dtype: float64

In [66]:
df

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  24.5     None
Store 1  Kevyn   Kitty Litter   4.5     None
Store 2  Vinod      Bird Seed   7.0     None

**Exportar Archivo**

In [67]:
import openpyxl 
import pandas as pd
data = {'first_name': ['Sigrid', 'Joe', 'Theodoric','Kennedy', 'Beatrix', 'Olimpia', 'Grange', 'Sallee'],
        'last_name': ['Mannock', 'Hinners', 'Rivers', 'Donnell', 'Parlett', 'Guenther', 'Douce', 'Johnstone'],
        'age': [27, 31, 36, 53, 48, 36, 40, 34],
        'amount_1': [7.17, 1.90, 1.11, 1.41, 6.69, 4.62, 1.01, 4.88],
        'amount_2': [8.06,  "?", 5.90,  "?",  "?", 7.48, 4.37,  "?"]}
df = pd.DataFrame(data, columns = ['first_name', 'last_name', 'age', 'amount_1', 'amount_2'])




**Exportar CSV**

In [68]:
df.to_csv(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\data_ejemplo_expor.csv', index = False) ## exportar csv

**Exportar Xlsx**

In [69]:
df.to_excel(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\example.xlsx', sheet_name='example')## Exportar en excel

## Importar Archivo

### Importar csv

In [70]:
df = pd.read_csv(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\olympics.csv')
df.head()

0         1     2     3     4      5         6     7     8  \
0                NaN  № Summer  01 !  02 !  03 !  Total  № Winter  01 !  02 !   
1  Afghanistan (AFG)        13     0     0     2      2         0     0     0   
2      Algeria (ALG)        12     5     2     8     15         3     0     0   
3    Argentina (ARG)        23    18    24    28     70        18     0     0   
4      Armenia (ARM)         5     1     2     9     12         6     0     0   

      9     10       11    12    13    14              15  
0  03 !  Total  № Games  01 !  02 !  03 !  Combined total  
1     0      0       13     0     0     2               2  
2     0      0       15     5     2     8              15  
3     0      0       41    18    24    28              70  
4     0      0       11     1     2     9              12

In [71]:
seguros = pd.read_csv(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\SEGURO1.csv',sep=";")
seguros.head()

Identificador  AcctAge  DDA   DDABal  CashBk  Checks  DirDep  NSF  NSFAmt  \
0              1      0.3    1   419.27       0       0       0    0     0.0   
1              2      0.7    1  1986.81       0       1       1    0     0.0   
2              4      0.5    1  1594.84       0       1       0    0     0.0   
3              5      6.7    1  2813.45       0       2       0    0     0.0   
4              6     12.3    1  1069.78       0      13       1    0     0.0   

   Phone  ...  CRScore  Moved  InArea  Ins  Branch  Res  Dep   DepAmt  Inv  \
0    0.0  ...    696.0      0       1    1     B17    R    2  1170.06  0.0   
1    0.0  ...    674.0      0       1    0      B2    R    1   446.93  0.0   
2    0.0  ...    672.0      0       1    0      B1    S    1  1144.24  0.0   
3    0.0  ...    648.0      0       1    1      B1    S    2  1208.94  0.0   
4    2.0  ...    662.0      0       1    1      B7    U    5  6813.58  0.0   

   InvBal  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0  

[5 rows x 49 columns]

In [72]:
cars = pd.read_csv(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\cars.csv')
cars.head(5)

YEAR        Make           Model        Size  (kW) Unnamed: 5 TYPE  \
0  2012  MITSUBISHI          i-MiEV  SUBCOMPACT    49         A1    B   
1  2012      NISSAN            LEAF    MID-SIZE    80         A1    B   
2  2013        FORD  FOCUS ELECTRIC     COMPACT   107         A1    B   
3  2013  MITSUBISHI          i-MiEV  SUBCOMPACT    49         A1    B   
4  2013      NISSAN            LEAF    MID-SIZE    80         A1    B   

   CITY (kWh/100 km)  HWY (kWh/100 km)  COMB (kWh/100 km)  CITY (Le/100 km)  \
0               16.9              21.4               18.7               1.9   
1               19.3              23.0               21.1               2.2   
2               19.0              21.1               20.0               2.1   
3               16.9              21.4               18.7               1.9   
4               19.3              23.0               21.1               2.2   

   HWY (Le/100 km)  COMB (Le/100 km)  (g/km)  RATING  (km)  TIME (h)  
0              2.4               2.1       0     NaN   100         7  
1              2.6               2.4       0     NaN   117         7  
2              2.4               2.2       0     NaN   122         4  
3              2.4               2.1       0     NaN   100         7  
4              2.6               2.4       0     NaN   117         7

In [73]:
censu = pd.read_csv(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\census.csv')
censu.head(3)

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
0        4779736            4780127          4785161  ...          0.002295   
1          54571              54571            54660  ...          7.242091   
2         182265             182265           183193  ...         14.832960   

   RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0         -0.193196          0.381066          0.582002         -0.467369   
1         -2.915927         -3.012349          2.265971         -2.530799   
2         17.647293         21.845705         19.243287         17.197872   

   RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  
0     1.030015     0.826644     1.383282     1.724718     0.712594  
1     7.606016    -2.626146    -2.722002     2.592270    -2.187333  
2    15.844176    18.559627    22.727626    20.317142    18.293499  

[3 rows x 100 columns]

**Importar XLSX**

In [74]:
df = pd.read_excel(r'D:\Usuarios\oscagaal\Documents\Diplomado_ML\INSUMOS\example.xlsx', sheet_name='example')
df.head(5)

Unnamed: 0 first_name last_name  age  amount_1 amount_2
0           0     Sigrid   Mannock   27      7.17     8.06
1           1        Joe   Hinners   31      1.90        ?
2           2  Theodoric    Rivers   36      1.11      5.9
3           3    Kennedy   Donnell   53      1.41        ?
4           4    Beatrix   Parlett   48      6.69        ?